
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLOR FORWARD LINECOLOR LOOP LPAREN NUMBER PEN RIGHT RPARENstatement : expression\n                  expression : LOOP NUMBER LPAREN stmnt RPAREN term expression\n                  | term LOOP NUMBER LPAREN stmnt RPAREN expression\n                  | stmnt\n                  | empty stmnt : stmnt FORWARD NUMBER term expression\n             | stmnt RIGHT NUMBER term expression\n             | term RIGHT NUMBER term expression\n             | term FORWARD NUMBER term expression\n             | expression\n             | empty term : PEN NUMBER COLOR LINECOLOR\n            | COLOR LINECOLOR PEN NUMBER\n            | PEN NUMBER\n            | COLOR LINECOLOR\n            | empty\n    empty :'
    
_lr_action_items = {'LOOP':([0,5,6,15,16,17,18,19,21,22,26,28,29,30,31,32,33,34,35,36,37,43,44,],[3,12,-16,-14,-15,3,-17,-17,-17,-17,12,-16,3,-16,3,3,3,3,-12,-13,-17,3,3,]),'PEN':([0,15,16,17,18,19,21,22,29,30,31,32,33,34,35,36,37,43,44,],[7,-14,24,7,7,7,7,7,7,-16,7,7,7,7,-12,-13,7,7,7,]),'COLOR':([0,15,16,17,18,19,21,22,29,30,31,32,33,34,35,36,37,43,44,],[8,23,-15,8,8,8,8,8,8,-16,8,8,8,8,-12,-13,8,8,8,]),'$end':([0,1,2,4,6,15,16,18,19,21,22,29,30,31,33,34,35,36,37,38,39,41,42,43,44,45,46,],[-17,0,-1,-4,-5,-14,-15,-17,-17,-17,-17,-17,-16,-17,-17,-17,-12,-13,-17,-6,-7,-8,-9,-17,-17,-2,-3,]),'FORWARD':([0,2,4,5,6,15,16,17,18,19,21,22,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,],[-17,-10,10,14,-5,-14,-15,-17,-17,-17,-17,-17,10,14,-10,-5,-17,-16,-17,-17,-17,-17,-12,-13,-17,-6,-7,10,-8,-9,-17,-17,-2,-3,]),'RIGHT':([0,2,4,5,6,15,16,17,18,19,21,22,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,],[-17,-10,11,13,-5,-14,-15,-17,-17,-17,-17,-17,11,13,-10,-5,-17,-16,-17,-17,-17,-17,-12,-13,-17,-6,-7,11,-8,-9,-17,-17,-2,-3,]),'NUMBER':([3,7,10,11,12,13,14,24,],[9,15,18,19,20,21,22,36,]),'RPAREN':([4,6,15,16,17,18,19,21,22,25,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,],[-4,-5,-14,-15,-17,-17,-17,-17,-17,37,-10,-5,-17,-16,-17,-17,-17,-17,-12,-13,-17,-6,-7,44,-8,-9,-17,-17,-2,-3,]),'LINECOLOR':([8,23,],[16,35,]),'LPAREN':([9,20,],[17,32,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,17,29,31,32,33,34,43,44,],[2,27,38,39,27,41,42,45,46,]),'stmnt':([0,17,29,31,32,33,34,43,44,],[4,25,4,4,40,4,4,4,4,]),'term':([0,17,18,19,21,22,29,31,32,33,34,37,43,44,],[5,26,29,31,33,34,5,5,26,5,5,43,5,5,]),'empty':([0,17,18,19,21,22,29,31,32,33,34,37,43,44,],[6,28,30,30,30,30,6,6,28,6,6,30,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','main.py',119),
  ('expression -> LOOP NUMBER LPAREN stmnt RPAREN term expression','expression',7,'p_expression','main.py',127),
  ('expression -> term LOOP NUMBER LPAREN stmnt RPAREN expression','expression',7,'p_expression','main.py',128),
  ('expression -> stmnt','expression',1,'p_expression','main.py',129),
  ('expression -> empty','expression',1,'p_expression','main.py',130),
  ('stmnt -> stmnt FORWARD NUMBER term expression','stmnt',5,'p_stmnt','main.py',133),
  ('stmnt -> stmnt RIGHT NUMBER term expression','stmnt',5,'p_stmnt','main.py',134),
  ('stmnt -> term RIGHT NUMBER term expression','stmnt',5,'p_stmnt','main.py',135),
  ('stmnt -> term FORWARD NUMBER term expression','stmnt',5,'p_stmnt','main.py',136),
  ('stmnt -> expression','stmnt',1,'p_stmnt','main.py',137),
  ('stmnt -> empty','stmnt',1,'p_stmnt','main.py',138),
  ('term -> PEN NUMBER COLOR LINECOLOR','term',4,'p_term','main.py',141),
  ('term -> COLOR LINECOLOR PEN NUMBER','term',4,'p_term','main.py',142),
  ('term -> PEN NUMBER','term',2,'p_term','main.py',143),
  ('term -> COLOR LINECOLOR','term',2,'p_term','main.py',144),
  ('term -> empty','term',1,'p_term','main.py',145),
  ('empty -> <empty>','empty',0,'p_empty','main.py',149),
]
